### ISSUE TITLE
Docker test_postgres

### ISSUE THREAD

**Issue by wisderfin** [kohiry/messenger#1]
Зачем создавать новую базу данных на другом порту с такими же параметрами что и основная, разве это не будет одна и та же база, но на разных портах? Если так и есть, то какой смысл вообще создавать бд для тестов, почему бы не использовать основную?

branch: main
path: docker-compose.yaml
string: 13-20

**Comment by kohiry** [comment]
Потому что в конфиге другие парам етры, глянь 
```
test_postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: test_${P_DB}  # here
      POSTGRES_USER: ${P_USER}
      POSTGRES_PASSWORD: ${P_PASS}
    ports:
      - "6000:5432"
```
